name: PR
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/**"
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: Install packages
        run: pnpm i
      - name: Codegen
        run: pnpm codegen
      - name: Build
        run: pnpm build
      #- name: Install subql-node-cosmos
      #  run: pnpm global add @subql/node-cosmos
      #- name: Run tests with Subquery Node
      #  run: subql-node-cosmos test -f ${{ github.workspace }}
